### ISSUE TITLE
How to use with Blazor WebAssembly

### ISSUE THREAD

**Issue by KillTrot** [smartive/zitadel-net#491]
I am currently trying to use Zitadel to authenticate users in a Blazor Webassembly App.

Is this possible with this package?

Do you have some guidance for it?

**Comment by buehler** [comment]
Hey @KillTrot 

I honestly don't know. In a [Blazor Server App](https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0#blazor-server) it should be possible, since everything is handled by the Kestrel server. On the other hand, in a [Blazor Webassembly App](https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0#blazor-server), I'm not really sure if it works.

What I found: [Authenticate a WebAssembly App with the Authenticator Package](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-7.0&tabs=visual-studio), so it seems that it is possible. However, you don't need the Zitadel package for it.

**Comment by KillTrot** [comment]
Hey @buehler 

Thank you very much for you answer.

I was able to find out the problem, but I was not able to find a solution yet.
The class [RemoteAuthenticationState ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.remoteauthenticationstate?view=aspnetcore-7.0) expects the state in the token response to contain the property "returnUrl" which is missing with zitadel.
Other providers (KeyCloak, Auth0, Authentik, IdentityServer etc.) provide the returnUrl.
This is why it throws an exception when trying to convert the state to a RemoteAuthenticationState.

Do you think I should open an issue in the zitadel repository?

**Comment by buehler** [comment]
I think this is more of a configuration issue. Do you have a demo-repository?

**Comment by KillTrot** [comment]
I quickly created one
Have a look here: https://github.com/KillTrot/Zitadel-BlazorWasm

**Comment by buehler** [comment]
So, I managed to get it working (for the Auth part at least). You need to add the following return Url in ZITADEL to your redirect urls: `https://localhost:5443/authentication/login-callback`. Afterwards, the login & redirect works. However, after the redirect (when fetching the user profile), the following error appears:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState.
```

**Comment by buehler** [comment]
Alright :) I think overwriting the default remote state object could be a good idea. My guess is, that in the OIDC Spec, the state is an arbitrary field and not necessarily an object with the return url.

**Comment by buehler** [comment]
Maybe it could help to have the "AddZitadelAuthentciatioN" for blazor apps.

**Comment by KillTrot** [comment]
Thanks very much for your invested time :)
